In [2]:
import numpy as np

In [3]:
stock_prices = np.random.randint(100, 500, (30, 5))
print(stock_prices)

[[286 471 254 107 157]
 [295 135 331 390 187]
 [203 298 199 200 102]
 [448 340 241 289 116]
 [181 298 137 236 122]
 [110 211 488 271 124]
 [223 313 340 106 362]
 [349 219 152 100 302]
 [107 353 399 411 341]
 [232 409 130 306 399]
 [369 430 248 374 115]
 [394 148 237 125 289]
 [112 321 406 260 244]
 [127 370 182 480 266]
 [361 134 496 242 392]
 [429 341 394 285 434]
 [429 323 449 488 499]
 [464 459 237 113 118]
 [190 346 328 444 190]
 [494 226 182 303 299]
 [319 240 193 395 487]
 [114 141 350 282 343]
 [307 415 342 357 252]
 [184 349 337 204 237]
 [274 316 270 151 249]
 [117 416 206 413 484]
 [164 271 298 321 364]
 [421 233 276 499 479]
 [265 142 366 397 201]
 [294 239 325 454 277]]


In [4]:
avg_prices = np.mean(stock_prices, axis = 0)
print(avg_prices)

[275.4        296.9        293.1        300.1        281.03333333]


In [5]:
max_price = np.max(stock_prices)
print(max_price)

499


In [6]:
day, company = np.unravel_index(np.argmax(stock_prices), stock_prices.shape)
print(f"Highest stock price: ${max_price:.2f} on Day {day}, Company {company}")

Highest stock price: $499.00 on Day 16, Company 4


In [6]:
min_val = stock_prices.min()
max_val = stock_prices.max()

normalized_prices = (stock_prices - min_val)/ (max_val - min_val)
print(normalized_prices)



[[0.51559032 0.82782963 0.45513444 0.14119675 0.33768119]
 [0.19134836 0.57911658 0.8236828  0.56106979 0.36050004]
 [0.15742871 0.81373358 0.20136052 0.05675853 0.67371895]
 [0.47429607 0.65905384 0.19427779 0.59397622 0.72271097]
 [0.49311624 0.30594279 0.66382184 0.21497512 0.24147601]
 [0.5063689  0.57606181 0.42271623 0.23982441 0.62781704]
 [0.19277895 0.35124125 0.30670415 0.79749965 0.97748732]
 [0.38283853 0.77766903 0.43201992 0.0941636  0.17628513]
 [0.87563446 0.16561741 0.14554984 0.4963605  0.24674464]
 [0.32855338 0.24653685 0.86516308 0.61529791 0.62583606]
 [0.24220969 0.9178061  0.95043983 0.34063019 0.78544425]
 [0.52032935 0.         0.94988451 0.28088904 0.90355914]
 [0.48733669 0.49780678 0.57329106 0.2009978  0.31350533]
 [0.88222548 0.20248668 0.80788402 0.84332801 0.86260756]
 [0.82724811 0.72256481 0.88017252 0.94589393 0.31639943]
 [0.34703957 0.37334031 0.75966268 0.87154143 1.        ]
 [0.70711081 0.00796366 0.19550969 0.71722485 0.3564136 ]
 [0.32261998 0

In [8]:
risky_days_mask = np.any(stock_prices < 200, axis=1)

print("Risky Investment Days:")
for day, is_risky in enumerate(risky_days_mask):
    if is_risky:
        risky_prices = stock_prices[day][stock_prices[day] < 200]
        risky_prices_rounded = [int(price) for price in risky_prices]
        print(f"Day {day}: {risky_prices_rounded}")


Risky Investment Days:
Day 0: [107, 157]
Day 1: [135, 187]
Day 2: [199, 102]
Day 3: [116]
Day 4: [181, 137, 122]
Day 5: [110, 124]
Day 6: [106]
Day 7: [152, 100]
Day 8: [107]
Day 9: [130]
Day 10: [115]
Day 11: [148, 125]
Day 12: [112]
Day 13: [127, 182]
Day 14: [134]
Day 17: [113, 118]
Day 18: [190, 190]
Day 19: [182]
Day 20: [193]
Day 21: [114, 141]
Day 23: [184]
Day 24: [151]
Day 25: [117]
Day 26: [164]
Day 28: [142]
